# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b06d85ff483cc7784088f7b1d28d07534c58511939603298666453156b949b8073f84df4c195d42a50c36ae13b48c73dec12743828fba2eecce7c3f58bbff95d

test:
  secret_key_base: 65103e6f89286512d8ab42c347149f2a68b5578e4a080412771639d643816b28d2ac58fa59b3e4ba83ad6399306310aad007be25207a30c8e0677a29700e1643

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
